language: python

os: linux
dist: focal
arch: amd64

cache: pip

env:
  global:
    # DRAFTABLE_TEST_ACCOUNT_ID
    - secure: "JZd9yaUYwpvg214d3X9xbLnPrCVJXWp4LbJisGaX9KQctFw+WzT1e06tJN8I/lhXzhZX3g3m1P3o3Yl9wHBeMf+kz8kzHLqmlFV6rjjfiO59pJsC6Q83HIfBL4hJU7r8jD9ij8oJ7WS+Tf8FDAY/iwKn5R1jQJ4EutyKdPYXmUJxZ4FrGyQo+ML7Dip83I0RDz5gCtRE62eD0IxziHfQXMfP0rvxWBHltc6z90S4AY14MZCTF2tZsv950rcx0CieF2FvA7rG6n92WgFSUHjv3peeR4Z0KYRTPZFWxXpRvlRbyqEDsXcw+I4GRthKjs0/gmdbKHV6C3QkmdjHekBPuQDREjcq9cOI5znuwyZFMiAl5jI0KzcDtjo2TflmuBqhgjHA6P1R9bflIBgia8cqiGk7md+zRde480o2o2STBj680xXQR8NMADHX+rYtK6b9lxblS5qxZAMznM7F+X14VyRVWeCbOyAg+N+n5FaxfKNLe4RFTxnE1FsJqzn1O57C+mZf1+TN83X18pYNG58sPNlzKWZtgDcPlyMj4EqibJtB5urnRRuFkHFeplCIr1+OIyET25KSACJffou65YX7ylP1wh8kHXjXGN5EWF7SegRJWEyEdg1EVbWE6Fl/rME432wzilxr2GGM5HrwQoted5Wliluqk5kVDvSrunM2mkI="
    # DRAFTABLE_TEST_AUTH_TOKEN
    - secure: "hj4HlZOf3SC6Ug2+4Gayvo+6NlzaZgPTRLu+h149sWmghxxsN3hjcuwmZZfnwBvMmJ4KM9U5I92atju8+GXysYe+rZg9jQ+9RRSedK7E0zHj0N/go8RZt7Ogfx+f2E3XR9862apDh7VUn4rrzJsK04XuS1zqZFCo9xw8DQqo4yl7OXaWD2tWZW7hRhUgOroDfosa358ZPCBaHCDBcRWV/k2/UE/7+UGmU96Ax+i51a+xQMya0YBDZrhFnyZycRaDsC1Uxs8prjStyTHXJ9t+ZIjx3G9v33UzOlGoPKJhHqHGPgwee1KkDa/y52fRY5s+9tKE2pvdA3b5cYL+dEgFwem7ZJvHhrRp9siY7BL0kI3tcAQjl7cMcNiN5eH0jN+Dw2wF6Dn3HceyHgNieL/OzH7uFKas0YCPTeX8mSoK32o4NKXA6o22WN49WkJmOs0lbNznXYfSun8Kox218qjV0RIQSvX/ag7sHmFeAMQZjxK11MzclmfGzWWSeCHAQDY4vVg7Yf18/EnL0bUi/ydT9r/FgdD6uMjZfGm1A3W1DbJdkl6q3L2IcS5d9rEatL/kkmcBrJE48L4kYWDepndZF4H+hjN4Nc8X8+xIohMkipfXMjSUmyLKR67kdz3F40Mc7eMId9o/Yeui7RGirTzCYvS4+ITo6TxLf33fExOJzZg="
    - TOX_TESTENV_PASSENV='DRAFTABLE_* CI CODECOV_* TRAVIS TRAVIS_*'

jobs:
  include:
    - name: Python 3.8
      python: '3.8'
      env: TOXENV=py38,coverage,codecov
    - name: Python 3.9
      python: '3.9'
      env: TOXENV=py39,coverage,codecov
    - name: Python 3.10
      python: '3.10'
      env: TOXENV=py310,coverage,codecov
    - name: Python 3.11
      python: '3.11'
      env: TOXENV=py311,coverage,codecov

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
  slack:
    rooms:
      - secure: eeujEPADw5Mu/ZkhyP6Ppj9xjPWh5qPbe6j2f29THZjlpIq2F9vCDsqtqJlvr7tom2WCsgIQT05yDY8yvc8DYEgaEkqF0U2BJ01XlUscVON6GaD3+Qhn9rxSJnJsfRVH0c417IO9ystliMrz4nMcE7Q6HhsCB61JTJ5t4Osi03VhNm40NyB8MouBSQKnPeAoZgJRiset2v+TrN2FO1Jm8el9m3uRxqaV1QWK609byAl0BYGxCZaly8HXMTlmJPXSOAv/gZH0O5sA4y9VrZYm+u/g7G5fi+CUfzuJUU1tgCtTK3hxiIUn/MDUDeHBz5LKYG8qQHUO+yGdD6mQVpzgiRlF83V60UFxpZgVh5ENuvNhFyxe/9x6ORjcrcSfNFk3gO50u59s58wqcvSxTRyx89xuVF9fDoxialD9vdo8xjEuEXCo+JZ+HQtwfHNp0b3nnPGQpgo+MMZQeWWPg5S1FsvJotutsuj0Nuq/lUQSsH7DjLOnzsXFOGv0rUrW/dE/s6OEYdIV0t4q6AagHCOlmjPDVTtOMEQZtb3tSv6sqvA6ogvgrjpFLeDqCZjuiJ9mUqzG+6hy4EhoINXGSEW1OF7q5mTcjCXwjfajxIdtSlj9kPctSAt605SdYgCD9GH2MTEmqCit1v2wndzJkwBsGESmKkvpwLoi4CwSmvbF0/4=
    on_success: never
    on_failure: always
